#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xgo_py
  
  rm -rf build/* tmp/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ src/xgo src/ant2xgo src/xgo2ant src/xgo2py tox.ini requirements.txt test_requirements.txt setup.py
else
  echo "DEV_BASE is not defined"
fi
