#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xgo_py
  
  rm -rf build/* tmp/* 
  
  pySloc -L py ant2xgo xgo2ant xgo2py  -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
